name: "Doc"

on:
  push:
    paths:
      - ".github/**/*"
      - "src/*"
      - "src/**/*"

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      "id-token": write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.8

      - run: bun install
      - run: bun run build
      - run: bun run build:docs
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs'
      - uses: actions/deploy-pages@v2
        id: deployment
